titles:
  - id: 101
    name: "ゼルダの伝説 BotW"
  - id: 102
    name: "マリオパーティ"
  - id: 103
    name: "スプラトゥーン3"
  - id: 104
    name: "ペルソナ5"
  - id: 105
    name: "スマブラSP"
  - id: 106
    name: "あつまれどうぶつの森"